[build]
  base = "control-panel"
  command = "pnpm build"
  publish = ".next"
[functions]
  directory = "netlify/functions"
[plugins]
  package = "@netlify/plugin-nextjs"
[build.environment]
  NODE_VERSION = "20"